################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
CMSIS-DSP/Source/FilteringFunctions/%.o CMSIS-DSP/Source/FilteringFunctions/%.su CMSIS-DSP/Source/FilteringFunctions/%.cyclo: ../CMSIS-DSP/Source/FilteringFunctions/%.c CMSIS-DSP/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../CMSIS-DSP/Include -I../CMSIS-DSP/PrivateInclude -I../CMSIS-DSP/ComputeLibrary/Include -I../Core/Inc -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Drivers/BSP/Components/lan8742 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-CMSIS-2d-DSP-2f-Source-2f-FilteringFunctions

clean-CMSIS-2d-DSP-2f-Source-2f-FilteringFunctions:
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.o
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-CMSIS-2d-DSP-2f-Source-2f-FilteringFunctions

